### ISSUE TITLE
Assumptions in __process

### ISSUE THREAD

**Issue by wwj718** [operand/agency#148]
__process assumes that the [result of self.__commit(message)](https://github.com/operand/agency/blob/main/agency/agent.py#L347) is response.

Imagine the following use case (this is my real use case): there is a manager agent that receives a message from a customer agent, the manager agent delegates the task to the workers agent (by forwarding the message), and the final response is sent from the worker agent to the customer agent. This assumption of __process makes things like this difficult

**Comment by wwj718** [comment]
A temporary solution I thought of is

```python
            return_value = self.__commit(message)
            if return_value == "__NOT_RESPONSE":
                # Wrap __NOT_RESPONSE into a better constant
                return
```

**Comment by operand** [comment]
Can you explain a bit more? I think I might need to see more detail to understand the issue.

**Comment by wwj718** [comment]
```
agentA
    send to agentB: make_pies

agentB(manager)
    @action
    def make_pies():
        # Delegate agentC to make pies
        send to agentB: make_pies(with the same meta.id)

agentC(worker)
    @action
    def make_pies():
        send the pie response with meta.id
```

The idea here is that agentB should not default the result of make_pies as response, or allow the user to specify whether the result of make_pies is response.

**Comment by wwj718** [comment]
[return_value is not None](https://github.com/operand/agency/blob/v1.4.1/agency/agent.py#L347) seems like a good solution.

**Comment by operand** [comment]
If I understand correctly the intention is to have Agent3 see the message as though it came from Agent1, and then send its return value back directly to Agent1. This won't work currently for a couple reasons.

One problem is that Agent2's proxy behavior is not fully possible because the `from` field is NOT overwritable.

The `from` field is set automatically upon sending [in the `send()` method](https://github.com/operand/agency/blob/main/agency/agent.py#L225C36-L225C36). So even if you try to overwrite it, the framework will silently "fix" it for you. I think I should update the docs to make this clear, and I can add an error or warning if you try to do this. In fact the way it currently stands, you should never set the `from` field manually.

This behavior was a deliberate choice. I'm not sure it's a good idea to allow agents to "impersonate" other agents by overwriting the `from` field. I think it's important to record the actual sender accurately. This allows for `response` behavior to work and I feel is more consistent/predictable so I'm hesitant to change this.

So Agent3 will see that the message came `from: Agent2` and not `from: Agent1`, and that's where its return value will go.

Though I can see why one might want to allow delegation of a task to other agents and have them respond directly to the original requestor (Agent1). I think we can come up with an acceptable pattern to do this. I have a few ideas.

One possibility would be to simply pass an argument to the worker indicating the original sender that it should reply to. For example:

```python
class Agent1(Agent):
    def order_pie(self):
        self.send({
            "to": "Agent2",
            "action": {
                "name": "order_pie"
            }
        })

    # We add this action to receive the pie from the worker
    @action
    def receive_pie(self, pie):
        self.pie = pie

class Agent2(Agent):
    @action
    def order_pie(self):
        self.send({
            "to": "Agent3", # delegate pie making to Agent3
            "action": {
                "name": "make_pies"
                "args": {
                    # Notice this customer_id arg, specifying the original sender
                    "customer_id": self.current_message()["from"],
                }
            }
        })

class Agent3(Agent):
    @action
    def make_pies(self, customer_id):
        # Here we send the pie to the provided customer
        self.send({
            "to": customer_id,
            "action": {
                "name": "receive_pie"
                "args": {
                    "pie": "🥧"
                }
            }
        })
```

This would ignore the use of response messages and accomplish it using only `send()`. I think this is a reasonable approach.

Another idea, instead of an explicit argument to the worker, we could also use a meta field for this scenario:

```python
class Agent1(Agent):
    def order_pie(self):
        self.send({
            "to": "Agent2",
            "action": {
                "name": "order_pie"
            }
        })

    def handle_action_value(self, value):
        # Here we receive the return value from the worker
        if self.parent_message()["action"]["name"] == "make_pie":
            self.pie = value

class Agent2(Agent):
    @action
    def order_pie(self):
        self.send({
            "meta": {
                # Notice this "respond_to" field, indicating where the response should go
                "respond_to": self.current_message()["from"]
            }
            "to": "Agent3", # delegate pie making to Agent3
            "action": {
                "name": "make_pies"
            }
        })

class Agent3(Agent):
    @action
    def make_pies(self, customer_id):
        # This would replace a "return" statement, OR we could update the
        # __process implementation to make use of the "respond_to" field and do
        # this automatically from a normal return statement.
        self.respond_with({
            "value": "🥧"
        })

    def respond_with(self, response):
        self.send({
            "to": self.current_message()["meta"]["respond_to"],
            "action": {
                "name": "[response]" # the special response action
                "args": response
            }
        })
```

A third possibility is to not use a delegator agent at all. It may not be necessary if Agent1 can send directly to Agent3. In this case, we can use responses to simplify our code.

```python
class Agent1(Agent):
    def order_pie(self):
        self.send({
            "to": random.choice(self.workers), # pick a worker
            "action": {
                "name": "make_pie"
            }
        })

    def handle_action_value(self, value):
        # Here we receive the return value from the worker
        if self.parent_message()["action"]["name"] == "make_pie":
            self.pie = value

class Agent3(Agent):
    @action
    def make_pies(self, customer_id):
        # Here we can simply return the value from the function
        return "🥧"
```

Depending on the use case, this might also be a fair approach.

What do you think? Did I capture the problem here?

**Comment by wwj718** [comment]
@operand Thank you for your proposed solutions, they provide great ideas to solve this problem.It made me realize the flexibility of the agency.

I think my previous formulation of the problem was not clear enough and I simplified the problem in an inappropriate way. In my use case, Agent1 is an OpenAIFunctionAgent and several of the current methods seem to require modifications to the OpenAIFunctionAgent.

We may realize that the current design is difficult to support things like proxy or caching. The restrictions on "from" and the fact that response is assumed to be the first action to respond to it seem to be the main reasons.

The end-to-end principles of the Internet encourage a "stupid network", and if we want security, the way Internet's handled is to add a cryptographic mechanism (a new layer) without forcing interference with the message structure. It's not clear to me whether this can be supported "from" can be modified。

**Comment by wwj718** [comment]
[return_value is not None](https://github.com/operand/agency/blob/v1.4.1/agency/agent.py#L347) is a smaller issue, does it need to revert to the previous?

```python
            return_value = self.__commit(message)

            # If the action returned a value or this was a request (which
            # expects a value), return it
            if return_value is not None:
                self.send({
                    "meta": {
                        "response_id": response_id
                    },
                    "to": message['from'],
                    "action": {
                        "name": _RESPONSE_ACTION_NAME,
                        "args": {
                            "value": return_value,
                        }
                    }
                })
```

Originally your solution seemed more reasonable, but the default return value I proposed later felt bad.

If the user wishes to return action completed information without substance, they can do so by `return ""`. The default return value of the function is None, which means it is not completed (this is enough to support the delegation I need).

**Comment by operand** [comment]
I'm glad the solutions above helped.

Can you expand on why returning `None` by default is causing a problem? I'd like to understand the situation better.

I'm okay with reverting if necessary! This is experimentation and I'm here for it! :)

**Comment by operand** [comment]
I've had a similar thought to your suggestion of using `return ""`. We can adopt a convention where `None` assumes nothing was returned, as in there was no explicit return value. And we can define a constant like `NoneValue` that is intended to be used when the function really means to return the value `None`.

Another similar idea: We could say that to respond with a value one needs to call a specific method like the `respond_with` method above.
```python
def my_action():
  ...
  self.respond_with(value)
```
In this case, the function's return value is discarded. This would have the benefit of being explicit and pretty clear. I'm starting to think this might be the right choice?

This little dilemma is unfortunate, and is due to the fact that we can't know if the method intentionally returned `None` or didn't return at all. The same situation is true in Javascript, so it's good to brainstorm on an acceptable approach, if we can find one.

Of course it should also be mentioned that this whole notion of "response" messages is just an added convention on top of the actor model that we're using as a way to reduce boilerplate for function calls. But we could always decide to pull back and only support a fully async approach. I'd prefer to support this if possible though.

**Comment by wwj718** [comment]
> In this case, the function's return value is discarded. This would have the benefit of being explicit and consistent. I'm starting to think this might be the right choice?

I totally agree with you, I think this design is very elegant. The requirement here is to explicitly hand over control to the user. Explicit is better than implicit.

> Of course it should also be mentioned that this whole notion of "response" messages is just an added convention on top of the actor model that we're using as a way to reduce boilerplate for function calls. But we could always decide to pull back and only support a fully async approach. I'd prefer to support this if possible though.

Very clear explanation, again I strongly agree.  The actor model is asynchronous in nature, synchronization should be treated as a special case, and it should be implemented on the surface as much as possible. As you said "we could always decide to pull back and only support a fully async approach. "

**Comment by operand** [comment]
Sounds good. I agree I think the `respond_with` idea feels right.

I'm working through the changes to allow foreground agents again and I'll make this part of the same update.

Thanks as always for brainstorming with me!

**Comment by wwj718** [comment]
> Can you expand on why returning None by default is causing a problem?

Returning None by default will cause the sender to think that the action is completed, but in fact the task is passed to other worker. As long as the worker has the original message id, it has the ability to inform the original sender of the task progress. But the first action to receive the message should not assume that the task is completed by default after running the function. So using `self.respond_with(value)` explicitly is more flexible.

**Comment by operand** [comment]
Now I understand. Thanks I needed that explanation. :)
